### ISSUE TITLE
TypeError: this.items.slice is not a function

### ISSUE THREAD

**Issue by cheey2003** [WPFreighter/wp-freighter#19]
Hi Austin,

Thanks so much for the updates! However, when I updated the plugin to v1.4, I discovered the following JS error on the Settings page and the stacked sites list are not showing. This may due to a backend API change as the site list is showing again after I have downgraded to v1.2

TypeError: this.items.slice is not a function
    filteredItems https://thisismydomain.com/wp-content/plugins/wp-freighter/assets/js/vuetify.min.js?ver=2.6.13:6
    VueJS 3
    computedItems https://thisismydomain.com/wp-content/plugins/wp-freighter/assets/js/vuetify.min.js?ver=2.6.13:6
    VueJS 90
    <anonymous> https://thisismydomain.com/wp-content/plugins/wp-freighter/assets/js/admin-app.js?ver=1.3.0:1
[vue.min.js:11:22592](https://subsite.dev/wp-content/plugins/wp-freighter/assets/js/vue.min.js?ver=2.7.16)

**Comment by austinginder** [comment]
Just released v1.5.0: https://github.com/WPFreighter/wp-freighter/releases. Give that try and let me know if you still have any issues.

**Comment by cheey2003** [comment]
Thanks again for taking a look at the issue! It is working well now 🎉
